### ISSUE TITLE
#limited message: 'Rate limit reached for default-gpt-3.5-turbo in organization org-on requests per min. Limit: 20 / min. Current: 30 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.',

### ISSUE THREAD

**Issue by joostshao** [gnehs/subtitle-translator#1]
message: 'Rate limit reached for default-gpt-3.5-turbo in organization org-on requests per min. Limit: 20 / min. Current: 30 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.',

**Comment by joostshao** [comment]
限速？

**Comment by gnehs** [comment]
![image](https://user-images.githubusercontent.com/16719720/223012426-d9566732-26ed-4fab-9b96-14cf44c07c53.png)

I have been sending about 200 requests within five minutes without any issues. You may need to add a payment method to your account to increase your rate limit.

**Comment by joostshao** [comment]
money is power
