### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by redscience** [gnehs/subtitle-translator#5]
I got this error message

file:///~/subtitle-translator/index.js:43
    let result = completion.data.choices[0].message.content
                                        ^

TypeError: Cannot read properties of undefined (reading '0')
    at file:///~/subtitle-translator/index.js:43:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by gnehs** [comment]
Please try again. If the issue persists, please provide me with your subtitle file and target language.
